[tool.black]
line-length = 90

[tool.ruff]
line-length = 90

select = [
    "F",
    "E",
    "I",
    "D",
    "U",
    "N",
    "C",
    "B",
    "A",
    "I25",
    "Q",
    "ANN",
    "C90",
    "RUF",
    "M",
]
ignore = ["D212", "D203"]
